### ISSUE TITLE
Breakage with `mtl-2.3-rc3`

### ISSUE THREAD

**Issue by andreasabel** [haskell/random#126]
See 
  - https://github.com/haskell/mtl/issues/86
  - https://github.com/haskell/mtl/issues/101#issuecomment-1044904781
  
Building with `mtl-2.3-rc3` fails:
```
[4 of 4] Compiling System.Random.Stateful ( src/System/Random/Stateful.hs, dist/build/System/Random/Stateful.o, dist/build/System/Random/Stateful.dyn_o )

src/System/Random/Stateful.hs:289:22: error:
    • Variable not in scope: replicateM :: Int -> m0 a0 -> m [a]
    • Perhaps you meant ‘replicate’ (imported from Prelude)
    |
289 | uniformListM n gen = replicateM n (uniformM gen)
    |                      ^^^^^^^^^^
Error: cabal: Failed to build random-1.2.1
```

**Comment by Bodigrim** [comment]
This is already fixed in #125, but I don't want to release it until `mtl-2.3` is actually finalised.

**Comment by andreasabel** [comment]
Ah sorry, didn't look through the PRs, only through the issues.
Yeah, would be great if we finally knew what the plan for `mtl-2.3` is.

I suppose you could release now, and in the unlikely case that it fails to build with the actually released `mtl-2.3`, restrict back to `<2.3` via a revision. 
This would make testing packages with `mtl-2.3-rc3` easier.

(Btw, I support your position of releasing `mtl-2.3` just to allow `tranformers-0.6`, and deal with the PVP issues (reexports) later.)
